### ISSUE TITLE
Follow redirects

### ISSUE THREAD

**Issue by dentarg** [twingly/feedbag.herokuapp.com#1]
E.g. https://feedbag.herokuapp.com/?url=https%3A%2F%2Fbloggvarldsbloggen.wordpress.com%2F

https://bloggvarldsbloggen.wordpress.com/ redirects to http://blogg.bloggportalen.se/ (https://feedbag.herokuapp.com/?url=blogg.bloggportalen.se)

**Comment by roback** [comment]
Redirection has been solved in feedbag 0.9.6 (https://github.com/damog/feedbag/commit/f1b6a88faf93d0841dbd6414a5ffa57997d957ca), which is the version we have had for some time.

The example in the description doesn't work anymore so I have not tested it, but I'll close this anyway 🙈
