### ISSUE TITLE
Automatic deploy broken

### ISSUE THREAD

**Issue by walro** [twingly/feedbag.herokuapp.com#3]
It didn't auto-deploy for me last time.

**Comment by jage** [comment]
It was indeed broken, the repository didn't have the webhook notifying Heroku of activity. I've reconnected the Heroku <-> GitHub deploy-connection. Also added HipChat notifications.

![screen shot 2016-04-01 at 21 48 07](https://cloud.githubusercontent.com/assets/7913/14218291/7fede7ae-f853-11e5-9442-7d3ad8d86b7e.png)
